server:
  port: 8080

spring:
  application:
    name: remitro-gateway

  app:
    auth:
      # 화이트리스트를 yml에서 관리
      whitelist:
        - /api/v1/auth/login
        - /api/v1/members/signup

  cloud:
    gateway:
      # 세션/쿠키 기반 접근 완전 차단
      default-filters:
        - RemoveRequestHeader=Cookie

      routes:
        # 1. 회원 서비스 (Member Service)
        - id: member-service
          uri: lb://remitro-member
          predicates:
            - Path=/api/v1/members/** # /api/v1/members로 시작하는 모든 요청을 가로챔
          filters:
            - RewritePath=/api/v1/members/(?<segment>.*), /${segment} # /api/v1/members를 떼고 실제 서비스에 전달

        # 2. 계좌 서비스 (Account Service)
        - id: account-service
          uri: lb://remitro-account
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - RewritePath=/api/v1/accounts/(?<segment>.*), /${segment}

        # 3. 거래 서비스 (Transaction Service)
        - id: transaction-service
          uri: lb://remitro-transaction
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - RewritePath=/api/v1/transactions/(?<segment>.*), /${segment}

logging:
  level:
    # 게이트웨이의 라우팅 로그를 상세히 확인하기 위함
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO

    com.remitro: DEBUG
