server:
  port: 8080

spring:
  application:
    name: remitro-gateway

  app:
    auth:
      # 화이트리스트를 yml에서 관리
      whitelist:
        - /api/v1/auth/login
        - /api/v1/members/signup

  cloud:
    gateway:
      # 세션/쿠키 기반 접근 완전 차단
      default-filters:
        - RemoveRequestHeader=Cookie

      discovery:
        locator:
          # 서비스 ID를 소문자로 매핑하도록 허용
          lower-case-service-id: true

eureka:
  instance:
    # 서비스 인스턴스를 호스트 이름이 아닌 IP 주소로 등록 (Docker/운영 환경에서 필수)
    prefer-ip-address: true

  client:
    # 유레카 서버에 자신을 등록할지 여부
    register-with-eureka: true

    # 유레카 서버로부터 다른 서비스 정보를 가져올지 여부
    fetch-registry: true

    # 5초마다 유레카 서버가 뜨는 동안 게이트웨이가 기다리거나 재시도
    registry-fetch-interval-seconds: 5

    service-url:
      # 유레카 서버의 위치 (Discovery 서버에서 사용할 기본 포트 8761)
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    # 게이트웨이의 라우팅 로그를 상세히 확인하기 위함
    org.springframework.cloud.gateway: TRACE
    com.remitro: DEBUG

jwt:
  # 최소 256bit (32자 이상) 필수
  secret: "secret-key-secret-key-secret-key-secret-key-secret-key"
